### ISSUE TITLE
gmake needed on FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [spiritloose/Compress-Zstd#4]
The zstd Makefiles only work with GNU make. On FreeBSD 10.x systems the build works if the following patch is applied:
```
diff --git a/builder/MyBuilder.pm b/builder/MyBuilder.pm
index 54231c0..90f833e 100644
--- a/builder/MyBuilder.pm
+++ b/builder/MyBuilder.pm
@@ -39,7 +39,7 @@ sub ACTION_build {
     $self->ACTION_ppport_h() unless -e 'ppport.h';
     unless (-f "$LIBZSTD_DIR/libzstd.a") {
         local $ENV{CFLAGS} = '-O3 -fPIC';
-        $self->do_system('make' => '-C', $LIBZSTD_DIR, 'libzstd.a');
+        $self->do_system('gmake' => '-C', $LIBZSTD_DIR, 'libzstd.a');
     }
     $self->SUPER::ACTION_build();
 }
```
Probably this should be made conditional (e.g. using `$^O =~ /bsd/` --- other BSDs also don't have GNU make installed by default) and probably a check for an existing `gmake` has to be done first.

**Comment by eserte** [comment]
Just stumbled over a PR for the same issue: https://github.com/spiritloose/Compress-Zstd/pull/1

**Comment by spiritloose** [comment]
Thank you for your report.
Applied in #9 .
